# -*- coding: utf-8 -*-
"""road_accident.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1erfVDhcVz85TqhvbXonqPJl0Ex7iMR3w
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files

# Commented out IPython magic to ensure Python compatibility.
# Set visualization style
# %matplotlib inline
sns.set_style('whitegrid')

# Run this cell to upload your CSV file
uploaded = files.upload()

!pip install openpyxl

df = pd.read_excel("Road Accident Data.xlsx")

df.head()

df.info()
df.isnull().sum()
df['Accident Date'] = pd.to_datetime(df['Accident Date'])
df['Hour'] = pd.to_datetime(df['Time'], errors='coerce').dt.hour
df['Month'] = df['Accident Date'].dt.month
df['Weekday'] = df['Accident Date'].dt.day_name()

df['Local_Authority_(District)'].value_counts().head(10)

df['Accident_Severity'].value_counts(normalize=True) * 100

import matplotlib.pyplot as plt

df.groupby('Month').size().plot(kind='line', title='Monthly Accident Trend')
plt.xlabel('Month')
plt.ylabel('Accidents')
plt.show()

import folium
from folium.plugins import HeatMap

# Filter to avoid NaNs
map_df = df[['Latitude', 'Longitude']].dropna()

m = folium.Map(location=[map_df['Latitude'].mean(), map_df['Longitude'].mean()], zoom_start=10)
HeatMap(map_df.values, radius=10).add_to(m)
m

df.to_csv("cleaned_road_accident_data.csv", index=False)

from google.colab import files
files.download("cleaned_road_accident_data.csv")